# Generated by Django 4.0.6 on 2022-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
