# Generated by Django 4.0.6 on 2022-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomcontent',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
